project:
  type: book

book:
  favicon: images/apple-touch-icon.png
  title: "rOpenSci Translation Guidelines"
  author-meta: "Yanina Bellini Saibene, MaÃ«lle Salmon, Paola Corrales, Elio Campiteli"
  code-link: true
  description-meta: |
    How we translate our material.
  reader-mode: true
  site-url: https://translationguide.ropensci.org/
  repo-url: https://github.com/ropensci-review-tools/translation_guide/
  repo-actions: [edit, issue]

  chapters:
  - index.Rmd
  - motivation.Rmd
  - general_guidelines_intro.Rmd
  - general_guidelines_internationalization.Rmd
  - general_guidelines_localization.Rmd
  - general_guidelines_howtoreview.Rmd
  - guidelines_spanish_specific_guidelines.Rmd
  - glossary.Rmd
  - booknews.Rmd

format:
  html:
    theme: [cosmo, custom.scss]
    code-link: true
    include-in-header: "matomo.html"
